#!/usr/bin/bash
# author: IndoKarjok
echo "\a"
read -p "Yakin Install Facebook tool? [y/n] " kontol;

if [ $kontol = Y ] || [ $kontol = y ]
then

     echo "starting..."
     sleep 0.7
 clear
     echo "\a"
     echo '\033[1;36mSabar...\033[0;00m'
     clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo 'Starting tools... -';
sleep 0.1;
clear
echo 'sTarting tools... \';
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo 'staRting tools... -';
sleep 0.1;
clear
echo 'starTing tools... \';
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo 'startinG tools... \';
sleep 0.1;
clear
echo 'starting Tools... -';
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo 'starting toOls... -';
sleep 0.1;
clear
echo 'starting tooLs... \';
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "[#...................]5%";
sleep 0.2;
clear
echo '[##..................]10%';
sleep 0.1;
clear
echo '[###.................]15%';
sleep 0.1;
clear
echo "[####................]20%";
sleep 0.1;
clear
echo '[#####...............]25%';
sleep 0.1;
clear
echo '[######..............]30%';
sleep 0.1;
clear
echo "[#######.............]35%";
sleep 0.1;
clear
echo '[########............]40%';
sleep 0.1;
clear
echo '[#########...........]45%';
sleep 0.1;
clear
echo "[##########..........]50%";
sleep 0.1;
clear
echo '[###########.........]55%';
sleep 0.1;
clear
echo '[############........]60%';
sleep 0.1;
clear
echo "[#############.......]65%";
sleep 0.1;
clear
echo '[##############......]70%';
sleep 0.1;
clear
echo '[###############.....]75%';
sleep 0.1;
clear
echo "[################....]80%";
sleep 0.1;
clear
echo '[#################...]85%';
sleep 0.1;
clear
echo '[##################..]90%';
sleep 0.1;
clear
echo '[###################.]95%';
sleep 0.1;
clear
echo "[####################]100%";
sleep 0.3;
clear
echo " \033[32m ________________             ";
echo '         < ACCSESS DANIED >            ';
echo '          ----------------             ';
echo '             \   ,__,                  ';
echo '              \  (oo)____              ';
echo '                 (__)    )\            ';
echo '                    ||--|| *           ';
sleep 0.2;
clear
echo " \033[32m ________________             ";
echo '         < ACCSESS DANIED >            ';
echo '          ----------------             ';
echo '             \   ,__,                  ';
echo '              \  (--)____              ';
echo '                 (__)    )\            ';
echo "                    ||--|| *           ";
sleep 0.2;
clear
echo " \033[32m ________________             ";
echo '         < ACCSESS DANIED >            ';
echo '          ----------------             ';
echo '             \   ,__,                  ';
echo '              \  (oo)____              ';
echo '                 (__)    )\            ';
echo '                    ||--|| *           ';
sleep 0.2;
clear
echo " \033[32m ________________             ";
echo '         < ACCSESS DANIED >            ';
echo '          ----------------             ';
echo '             \   ,__,                  ';
echo '              \  (--)____              ';
echo '                 (__)    )\            ';
echo '      Mwoooh        ||--|| *           ';
sleep 0.3;
clear
echo " \033[32m successful installed.        ";
sleep 0.2;
clear
echo ' \033[32m successful installed..        ';
sleep 0.2;
clear
echo " \033[32m successful installed...        ";
sleep 0.2;
clear

echo "\033[32m ===================== Welcome ===================";
echo '         [+] Coded : Tn.Herp                           ';
echo '         [+] Id Fb : Gwimusa3                          ';
echo '         [+] IG    : @Rezadkim                         ';
echo '         [+] WA    : 0895611252563 & 089620134992      ';
echo '         ------------------ FaceBook Tools ---------------';
echo '';
echo 'Nb: Pantad Typiz Dilarang Menggunakan Tools Ini!';
echo "    Atau akan terbully. Eh ntar malah nangid :v ";

fi

if [ $kontol = N ] || [ $kontol = n ]
then
     echo "Mampir lagiya Coeg :v "
fi