#!/usr/bin/bash
# author: IndoKarjok

clear
echo "starting tools... /";
sleep 0.1;
clear
echo "Starting tools... -";
sleep 0.1;
clear
echo "sTarting tools... \";
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo "staRting tools... -";
sleep 0.1;
clear
echo "starTing tools... \";
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo "startinG tools... \";
sleep 0.1;
clear
echo "starting Tools... -";
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo "starting toOls... -";
sleep 0.1;
clear
echo "starting tooLs... \";
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo "Starting tools... -";
sleep 0.1;
clear
echo "sTarting tools... \";
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo "staRting tools... -";
sleep 0.1;
clear
echo "starTing tools... \";
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo "startinG tools... \";
sleep 0.1;
clear
echo "starting Tools... -";
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo "starting toOls... -";
sleep 0.1;
clear
echo "starting tooLs... \";
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo "Starting tools... -";
sleep 0.1;
clear
echo "sTarting tools... \";
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo "staRting tools... -";
sleep 0.1;
clear
echo "starTing tools... \";
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo "startinG tools... \";
sleep 0.1;
clear
echo "starting Tools... -";
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo "starting toOls... -";
sleep 0.1;
clear
echo "starting tooLs... \";
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo "Starting tools... -";
sleep 0.1;
clear
echo "sTarting tools... \";
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo "staRting tools... -";
sleep 0.1;
clear
echo "starTing tools... \";
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo "startinG tools... \";
sleep 0.1;
clear
echo "starting Tools... -";
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo "starting toOls... -";
sleep 0.1;
clear
echo "starting tooLs... \";
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo "Starting tools... -";
sleep 0.1;
clear
echo "sTarting tools... \";
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo "staRting tools... -";
sleep 0.1;
clear
echo "starTing tools... \";
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo "startinG tools... \";
sleep 0.1;
clear
echo "starting Tools... -";
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo "starting toOls... -";
sleep 0.1;
clear
echo "starting tooLs... \";
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
echo "starting tools... /";
sleep 0.1;
clear
echo "Starting tools... -";
sleep 0.1;
clear
echo "sTarting tools... \";
sleep 0.1;
clear
echo "stArting tools... /";
sleep 0.1;
clear
echo "staRting tools... -";
sleep 0.1;
clear
echo "starTing tools... \";
sleep 0.1;
clear
echo "startIng tools... /";
sleep 0.1;
clear
echo "startiNg tools... -";
sleep 0.1;
clear
echo "startinG tools... \";
sleep 0.1;
clear
echo "starting Tools... -";
sleep 0.1;
clear
echo "starting tOols... /";
sleep 0.1;
clear
echo "starting toOls... -";
sleep 0.1;
clear
echo "starting tooLs... \";
sleep 0.1;
clear
echo "starting toolS... /";
sleep 0.1;
clear
